export const products = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 299.99,
    image: "/wireless-headphones-black.jpg",
    description: "High-quality sound with active noise cancellation",
    category: "electronics",
  },
  {
    id: "2",
    name: "Minimalist Watch",
    price: 149.99,
    image: "/minimalist-watch-gold.jpg",
    description: "Elegant timepiece with leather strap",
    category: "fashion",
  },
  {
    id: "3",
    name: "Wireless Charger Pad",
    price: 49.99,
    image: "/wireless-charger-pad-white.jpg",
    description: "Fast charging compatible with all devices",
    category: "electronics",
  },
  {
    id: "4",
    name: "Premium Sunglasses",
    price: 199.99,
    image: "/premium-sunglasses-uv.jpg",
    description: "UV protection with polarized lenses",
    category: "fashion",
  },
  {
    id: "5",
    name: "Leather Messenger Bag",
    price: 179.99,
    image: "/leather-messenger-bag.jpg",
    description: "Spacious compartments for work essentials",
    category: "fashion",
  },
  {
    id: "6",
    name: "Smart Fitness Band",
    price: 99.99,
    image: "/smart-fitness-band.jpg",
    description: "Track your health and activity goals",
    category: "electronics",
  },
  {
    id: "7",
    name: "Modern Coffee Table",
    price: 249.99,
    image: "/modern-coffee-table-wood.jpg",
    description: "Sleek design perfect for any living room",
    category: "home",
  },
  {
    id: "8",
    name: "Organic Face Serum",
    price: 89.99,
    image: "/organic-face-serum-bottle.jpg",
    description: "Hydrating serum with natural ingredients",
    category: "beauty",
  },
  {
    id: "9",
    name: "Wool Area Rug",
    price: 399.99,
    image: "/wool-area-rug-beige.jpg",
    description: "Premium quality handwoven rug",
    category: "home",
  },
  {
    id: "10",
    name: "Silk Pillowcase Set",
    price: 79.99,
    image: "/silk-pillowcase-white.jpg",
    description: "Luxurious silk for better sleep",
    category: "home",
  },
  {
    id: "11",
    name: "Professional Makeup Brush Set",
    price: 129.99,
    image: "/makeup-brush-set-professional.jpg",
    description: "12-piece professional makeup brushes",
    category: "beauty",
  },
  {
    id: "12",
    name: "Designer Perfume",
    price: 159.99,
    image: "/designer-perfume-bottle.jpg",
    description: "Luxury fragrance for all occasions",
    category: "beauty",
  },
]
